[package]
name = "dapp"
version = "1.0.0"
authors = []

[addresses]
revanth = "0x1d8ac78bfa38e97ebf3b2bb05886c9d666b854fd6c858f0217abcc7789b42217"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
