[package]
name = "dapp"
version = "1.0.0"
authors = []

[addresses]
revanth = "e5385db1465ff28c87f06296801e4861e238e8927c917e0af5d22151422dd495"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
